[package]
name = "pdm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = {version = "0.29.0", features = ["bundled", "chrono"]}
chrono = {version = "0.4", features = ["serde"]}
rocket = {version = "=0.5.0-rc.3", features = ["json"]}
serde = "1"